### ISSUE TITLE
Clicking on URLs/Links Do Not Open Tabs/Windows in Web Browser

### ISSUE THREAD

**Issue by TimmyzBeach** [edipox/wunderlistux#10]
The Windows & OS X versions of the official app open a new tab in the default web browser when you click on a link, either in the title or notes within the to-do.

If you can make your app do that too, that would be great!

Thanks for the work you've done on this by the way...

**Comment by edipox** [comment]
Thank you @TimmyzBeach I want to try that, but now I don't have a linux machine :/

**Comment by edipox** [comment]
So by now I'll add a _help wanted_ label and when I get my env working I'll try to fix this

**Comment by JakeC1020** [comment]
The solution to this seems to be an event listener for the [new-window](http://electron.atom.io/docs/api/web-view-tag/#event-new-window) event given by the web view tag. 

I have been successful getting this fix to work on my machine (x86_64 Mint) and will create a pull request with the fix.

**Comment by edipox** [comment]
Thank you very much @JakeC1020 I'll take a look

**Comment by edipox** [comment]
Changes for this issue are already in master thanks to @JakeC1020 
I'll try to build the releases from OS X (as I still don't have a Linux machine) and then close this issue

**Comment by JakeC1020** [comment]
Have you considered using a virtual machine to do Linux testing on?

**Comment by edipox** [comment]
Yes, I have and that's what I am going to do. I just wanted to test it in OS X so we don't have to wait until I finish to download the ISO

**Comment by edipox** [comment]
Just released the fix, so I am closing this issue
