### ISSUE TITLE
GitHub API access to releases

### ISSUE THREAD

**Issue by happydemic** [edipox/wunderlistux#13]
Thanks so much for this great project.

Would you consider adjusting the format of the Releases so that they can be accessed via the GitHub API? 

The API is really useful for users to script downloading release updates.

Currently, **https://api.github.com/repos/edipox/wunderlistux/releases** is an empty array (`[ ]`). GitHub sometimes displays projects as 'releases' on the web but does not include them as releases in the API.

According to **[this](https://github.com/bcit-ci/CodeIgniter/issues/3421#issuecomment-67481291)**, the issue can arise when a release has tags but no release notes.

**Comment by edipox** [comment]
Hi @happydemic Thank you very much!
I didn't know any of this, I'll take a look

**Comment by edipox** [comment]
I think it's done! I just added the latest release. But as soon as a new release "arrives" I will try to remember to keep adding the release notes so they will appear in the API.

**Comment by edipox** [comment]
Please @happydemic give some feedback so we can close this issue

**Comment by happydemic** [comment]
Thank you! Yep, that works.

**Comment by edipox** [comment]
Hi @happydemic I don't know what you were doing with github api and the releases URL, but I just wanted to let you know that I changed the format of the release, in the last one. I've attached the files to the release instead of creating a separate release for each file. 
Best regards

**Comment by happydemic** [comment]
@edipox Thanks for the heads up - all working fine. 

The API calls are just for my own personal updater script. The multiple attachments format is more common, and so simpler for parsing. Thanks!
