### ISSUE TITLE
Provide download of install.sh

### ISSUE THREAD

**Issue by xpilgrim** [edipox/wunderlistux#14]
Maybe, it could be helpful, when it's possible to provide a separate download for https://github.com/edipox/wunderlistux/blob/master/bin/install.sh. So, it's easy to install it for "non hacking kiddies"?

**Comment by edipox** [comment]
@xpilgrim Sorry I am not sure I understood what you mean. Do you mean to add that link in the README install instructions?

**Comment by xpilgrim** [comment]
The readme is a good place, but I tought it's possible to add the file as
separate  download in the releases.

Am 13.11.2016 20:19 schrieb "Edipo Vinicius da Silva" <
notifications@github.com>:

@xpilgrim https://github.com/xpilgrim Sorry I am not sure I understood
what you mean. Do you mean to add that link in the README install
instructions?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/edipox/wunderlistux/issues/14#issuecomment-260205959,
or mute the thread

**Comment by edipox** [comment]
@xpilgrim I've added the install script in both arch releases and in the README now it is a download link.

**Comment by xpilgrim** [comment]
Great! Thank you!
