### ISSUE TITLE
Permissions after install release 0.0.6

### ISSUE THREAD

**Issue by xpilgrim** [edipox/wunderlistux#15]
After installing release 0.0.6, /opt/wunderlistux/Wunderlistux hasn't permission for execute the file, also not libnode.so. 

I've installed 0.0.6 "over" 0.0.5 via the install.sh. Also when I delete /opt/wunderlistux/ before installing, the permissions are not set.

Where must it be fixed?

**Comment by edipox** [comment]
hmm I thought it was an issue with my VM. But as you are facing this issue too it means that there is a problem with files mode. Temporarily you could fix the issue by `sudo chmod 7777 -R /opt/wunderlistux` or something like that, or you could also try the AppImage. Thank you @xpilgrim very much for reporting this, I'll try to fix it soon.

**Comment by edipox** [comment]
Fixed. @xpilgrim  Could you test it so we can close this issue?

**Comment by xpilgrim** [comment]
Yes, I've tested in a VM and on normal install. Both works for me. Thank's a lot!
