### ISSUE TITLE
Make the AppImage downloadable

### ISSUE THREAD

**Issue by probonopd** [edipox/wunderlistux#16]
Looks like it can't be found on the Releases page?

**Comment by edipox** [comment]
@probonopd 
Currently is the AppImage 0.0.6 in https://github.com/edipox/wunderlistux/releases 
Here is the link: https://github.com/edipox/wunderlistux/releases/tag/0.0.6-AppImage

**Comment by edipox** [comment]
@probonopd  please give me your feedback to close this issue

**Comment by probonopd** [comment]
Hi @edipox unfortunately there is no AppImage for download, just source code:

![screenshot from 2016-11-15 18-13-50](https://cloud.githubusercontent.com/assets/2480569/20315751/503aeba0-ab5f-11e6-99f4-508e74ac6bb9.png)

**Comment by edipox** [comment]
@probonopd Well, it says "source code" because github thinks it's a bunch of code but it is actually the AppImage compressed.

**Comment by edipox** [comment]
I'll update the README to make it clearer

**Comment by probonopd** [comment]
Please upload the AppImage as a separate downloadable file. Not inside a .zip or .tar.gz.

You can use this feature on the Releases page when you click on "Edit":

![screenshot from 2016-11-15 18-33-18](https://cloud.githubusercontent.com/assets/2480569/20316419/07666e88-ab62-11e6-93fa-d1e812a38230.png)

**Comment by edipox** [comment]
@probonopd Oh.. good idea, thank you

**Comment by edipox** [comment]
@probonopd Done!

**Comment by edipox** [comment]
Now I have to rethink the way I am creating those releases to make it more organized :thinking:

**Comment by probonopd** [comment]
Thank you. It's running well for me now.
