### ISSUE TITLE
Adwaita theme

### ISSUE THREAD

**Issue by handicraftsman** [edipox/wunderlistux#17]
In vanilla GNOME3 there's only close button. And it's placed at right. Please, fix that. (adwaita theme is native to GNOME3)

**Comment by edipox** [comment]
@handicraftsman Just for curious. What does vanilla means in this case?

**Comment by edipox** [comment]
@handicraftsman With the last release you can customize the buttons position so this issue should be fixed, please take a look

**Comment by edipox** [comment]
I'll assume this work for you too. If there is some problem feel free to reopen this issue or to create a new one
