### ISSUE TITLE
Fix "drag to-dos to reorder"

### ISSUE THREAD

**Issue by edipox** [edipox/wunderlistux#2]
As explained here: http://www.omgubuntu.co.uk/2016/10/wunderlist-electron-app-linux drag and drop of todos isn't currently working

**Comment by awernick** [comment]
I was able to get drag and drop working by building the app on my local machine without modifying anything. Maybe the bug had to do with electron? 

This was tested in Arch Linux.

yarn.lock:
https://gist.github.com/awernick/b054522c64ce2b82d62f3f4597373e4c

**Comment by edipox** [comment]
Awesome! Thank you @awernick !
