### ISSUE TITLE
Show progress of wget in install-script.sh

### ISSUE THREAD

**Issue by tuaminx** [edipox/wunderlistux#22]
Please add `--show-progress --progress=bar:force` to wget at line 33 so that we know if it is downloading :)
`33  wget --show-progress --progress=bar:force -q -O /tmp/wunderlistux.tar.gz $URL`

```
Starting install of wunderlistux...                                 
Downloading package...                                              
/tmp/wunderlistux.tar.gz   10%[==>                                 ]  12.76M   114KB/s    eta 13m 17s
```

**Comment by edipox** [comment]
Nice, thanks @tuaminx

**Comment by tuaminx** [comment]
You are welcome :slightly_smiling_face:

**Comment by edipox** [comment]
Done!
