### ISSUE TITLE
No icon in panel

### ISSUE THREAD

**Issue by owcz** [edipox/wunderlistux#23]
The app shows the generic icon in my app/menu panel because none is specified in the new window function. Adding something like 
```js
    icon: __dirname + '/images/icon.png',
```
to `main.js`'s new window function should fix it. Also there's a typo in "transparent":

```js
  win = new BrowserWindow({
    // Min size
    minWidth: size.width,
    minHeight: size.height,
    // Window style
    transparent: true,
    frame: false,
    radii: [10,10,10,10],
    // Window state
    x: winState.x,
    y: winState.y,
    icon: __dirname + '/images/icon.png',
    width: winState.width,
    height: winState.height
  });
```

If more info is needed, I had previously addressed a similar issue in another electron app: https://github.com/Automattic/simplenote-electron/issues/316#issuecomment-292755435 (links to other similar threads in that comment)

Edit: I resolved this in test so will fix .desktop icon too and submit patch

**Comment by edipox** [comment]
Awesome! Thank you @owcz !
