### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by kvasko** [edipox/wunderlistux#25]
Hi,
Some days ago I downloaded this nice app. I have used it daily on my Ubuntu Linux 16.04 but since today morning I am getting the following error message when I try to start it:

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at validateState (/tmp/.mount_Gd9WDA/usr/bin/resources/app.asar/node_modules/electron-window-state/index.js:46:34)
    at module.exports (/tmp/.mount_Gd9WDA/usr/bin/resources/app.asar/node_modules/electron-window-state/index.js:154:3)
    at App.<anonymous> (/tmp/.mount_Gd9WDA/usr/bin/resources/app.asar/main.js:16:18)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

The above mentioned error message was sent by the Appimage but I got the same error when I tried to start the App which was installed by the dpkg command (deb package). Here it is:

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at validateState (/opt/Wunderlistux/resources/app.asar/node_modules/electron-window-state/index.js:46:34)
    at module.exports (/opt/Wunderlistux/resources/app.asar/node_modules/electron-window-state/index.js:154:3)
    at App.<anonymous> (/opt/Wunderlistux/resources/app.asar/main.js:16:18)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

I didn't find any useful solution on the internet; therefore I am requesting your help to solve this issue. I like this app and I would like to use it in the future as well. But currently it is not possible... :-(

**Comment by edipox** [comment]
Thank you @kvasko as soon as I have some time I'll try to reproduce this so I can fix the issue

**Comment by edipox** [comment]
@kvasko Very strange... I've tried it from the AppImage, the .deb installer and directly running the source code. But I wasn't able to reproduce the bug.. Do you have any other info or steps I could try?
We are using a library called electron-window-state which is very nice to manage and restore the window position, and things like that, it looks like somehow electron-window-state stored a wrong value. Maybe you could try removing the file `~/.config/Wunderlistux/window-state.json` or everything on `~/.config/Wunderlistux`. Please let me know if that fixes the issue so we can continue to investigate this

**Comment by edipox** [comment]
@kvasko Actually, before removing anything on `~/.config/Wunderlistux` would you to paste here the content of `~/.config/Wunderlistux/window-state.json`? and to copy`~/.config/Wunderlistux` to somewhere else so we don't loose the data

**Comment by christian-schwarzbauer** [comment]
@edipox I had the exact same problem as @kvasko, same stacktrace, same line numbers.
only difference: for me it happened on Antergos Linux with the version from the AUR (https://aur.archlinux.org/packages/wunderlistux-bin/).

however, removing the `window-state.json` file fixed the issue.
so here's the previous (seemingly corrupt) JSON:

```
{"width":1920,"height":524,"x":null,"y":186,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":2880,"y":0,"width":960,"height":600}}
```

and here's the re-created one:

```
{"width":1920,"height":524,"x":0,"y":0,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}}
```

I guess the `null` for the `x` position could have been the problem?
I have to mention that I did a lot of switching between HiDPI laptop and only FHD monitor resolution, both connected at the same time (Cinnamon on X11).

hope this helps!

**Comment by edipox** [comment]
Thank you @christian-schwarzbauer ! That will help 💯

**Comment by shivarajagopal** [comment]
Had the same issue, deleting ```window-state.json``` fixed it for me. I also use it with a HiDPI laptop and and a couple FHD monitors. Ubuntu 17.10 here.

**Comment by kontrollanten** [comment]
The used version for [electron-window-state](https://github.com/mawie81/electron-window-state) is 3.1.0, maybe an update to current latest, 5.0.3, will solve this?
