### ISSUE TITLE
How do i build it?

### ISSUE THREAD

**Issue by handicraftsman** [edipox/wunderlistux#4]
How do i build it? I am using i686 kernel.

**Comment by handicraftsman** [comment]
@edipox

**Comment by edipox** [comment]
Hi @handicraftsman 
You can edit the bin/build.sh file with your arch or just wait, in a few hours I'll create an script so you can build

**Comment by edipox** [comment]
@handicraftsman I've just added a new build script, you can run it `./bin/build-linux-ia32.sh`
It will generate a release folder and inside it will be the app.
Could you test it? I'll leave this issue meant to add a proper documentation about dependecies, build, etc

**Comment by handicraftsman** [comment]
`./build-linux-ia32.sh: line 4: electron-packager: command not found`
And there's no `electron-packager` even in AUR/NPM

**Comment by edipox** [comment]
Yes @handicraftsman , you are right first you have to install electron-packager with npm. Could you try the following:

```
npm install electron-packager -g
```

Thank you for your feedback

**Comment by edipox** [comment]
I don't remember well but I think you would also need to install electron: 

```
npm install -g electron
```

**Comment by handicraftsman** [comment]
I already have electron... And lel - i just typoed when tryed to install `electron-packager`

**Comment by handicraftsman** [comment]
Stop. Really? `build-win32.SH`?)

**Comment by edipox** [comment]
Cool! Please let me know if you can successfully build the app, because I would like to write some doc with all the required "steps" for contributors

**Comment by handicraftsman** [comment]
Works.

**Comment by handicraftsman** [comment]
Just run that script from repo root (not `bin/`).

**Comment by edipox** [comment]
Yeah, good catch

**Comment by handicraftsman** [comment]
build-win.sh

```
#!/bin/bash
APPNAME=Wunderlistux
VERSION=1.2.7
electron-packager . $APPNAME --platform=win32 --arch=x64 --version=$VERSION --overwrite=true --asar=false --app_version=0.0.1 --appname=$APPNAME --out=releases --overwrite=true --icon=images/app.ico
```

We also need `build-win-from-win.bat` :cat2:

**Comment by handicraftsman** [comment]
Ahh, also. I am writing trello-like (but more complex) task manager. Should i tell you when i'll make it work? (mb i'll never finish it)

**Comment by edipox** [comment]
@handicraftsman Yes, let me know. BTW What technology are you using in the server side?

**Comment by edipox** [comment]
Would you make a pull request with your build so I can create a release for ia32?

**Comment by handicraftsman** [comment]
Ok, wait

**Comment by handicraftsman** [comment]
Server-side: sinatra + erb (ruby). Client-side: materializeCSS, jQuery, reactJS, babel. Currently i am implementing session support.

**Comment by edipox** [comment]
@handicraftsman Cool, I have almost 5 years of experience with Ruby on Rails but never tried sinatra. I really would like to learn about those other ruby frameworks like sinatra and cuba. Recently I've been working in a project with Reactjs, babel, etc, and instead of materialize we use MDL and for the server we are using phoenix & elixir, here is the link https://github.com/iporaitech/pwr2-docker if you want to check it out

**Comment by handicraftsman** [comment]
@edipox, cool. But i am ignoring Docker, because cannot use it - you know that my kernel is i686. Also, sinatra-tutorials can be always found [here](http://www.sinatrarb.com/documentation.html). 

Also, Why sinatra? Just because it's much simpler and lighter than Rails. But i must write some functions from scratch (like DB-access, sessions etc)

P. S. I'll create repo when i'll make first working version

**Comment by edipox** [comment]
Closing this issue as I have added building info in the README
