### ISSUE TITLE
Minimize button and Remember Window size on close

### ISSUE THREAD

**Issue by 3err0** [edipox/wunderlistux#6]
Minimize button visible on diffirent window size

**Comment by handicraftsman** [comment]
1. And?
2. Can be added just by slightly editing configurator.
   (i am not good with electron, so, it's just my comment :D)

**Comment by handicraftsman** [comment]
@edipox

**Comment by edipox** [comment]
I am still thinking/designing a solution for the window buttons issue, because there are people wanting different layouts

**Comment by edipox** [comment]
@876974 For now if you are using the ubuntu's ambiance theme you could try the last release that includes this theme with the 3 buttons close, minimize, maximize.

**Comment by handicraftsman** [comment]
@edipox, just allow gtk-like widget restyling.

**Comment by edipox** [comment]
@handicraftsman Yeah, that's what I've thought too, but that means a lot of work, so I am still considering another strategy. But maybe I'll end up doing that anyway

**Comment by edipox** [comment]
@876974 I'm working in the window position/size issue, I'll release the fix soon

**Comment by edipox** [comment]
The window size & position is already working on master, but I couldn't release it yet because currently I don't have a Linux machine 😢

**Comment by handicraftsman** [comment]
@edipox, on linux electron uses GTK as it's engine.

**Comment by edipox** [comment]
@handicraftsman Oh, yes. But this app has its own window controls, because it is a frameless window. I did it a frameless windows because I wanted an app with something like CSD headerbars.

**Comment by edipox** [comment]
The window size and position issue is fixed and released. But there is a problem #15 with the release.

**Comment by edipox** [comment]
Fixed the problem I mentioned with the last release. I'll keep this issue open because in the last release we only fixed the issue about window size & position, but the minimize button configuration is still missing.

**Comment by edipox** [comment]
@876974 The last release fixes this issue, please take a look

**Comment by edipox** [comment]
![Screenshots](https://raw.githubusercontent.com/edipox/wunderlistux/master/images/settings-panel.png)

**Comment by edipox** [comment]
I'll assume this work for you too. If there is some problem feel free to reopen this issue or to create a new one
